"""Future Domain Interface: AIProvider

Defines the contract for LLM inference, multimodal reasoning, and streaming
to be implemented in Part 2.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, AsyncIterator


@dataclass
class AIProviderMetadata:
    """Metadata describing an AI provider and its model capabilities."""
    provider_name: str
    model_name: str
    context_window: int
    supports_streaming: bool = True
    supports_multimodal: bool = False
    supports_tool_calling: bool = False
    rate_limit_rpm: int | None = None


@dataclass
class AIGenerationResult:
    """Standardized response from AI text or multimodal generation."""
    content: str
    model: str
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    finish_reason: str = "stop"
    raw_response: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


class AIProvider(ABC):
    """Abstract interface contract for Jenna AI model backends.

    Implementations in Part 2 (e.g., Anthropic, OpenAI, Local Ollama/vLLM)
    must satisfy this contract.
    """

    @abstractmethod
    async def generate_text(
        self,
        prompt: str,
        context: list[dict[str, str]] | None = None,
        model: str | None = None,
        temperature: float = 0.7,
        max_tokens: int = 2048,
        **kwargs: Any,
    ) -> AIGenerationResult:
        """Generate complete text response for a given prompt and message history."""
        pass

    @abstractmethod
    def generate_stream(
        self,
        prompt: str,
        context: list[dict[str, str]] | None = None,
        model: str | None = None,
        temperature: float = 0.7,
        max_tokens: int = 2048,
        **kwargs: Any,
    ) -> AsyncIterator[str]:
        """Stream response tokens asynchronously as they are generated by the model."""
        pass

    @abstractmethod
    async def reason_multimodal(
        self,
        prompt: str,
        images: list[bytes | str],
        model: str | None = None,
        **kwargs: Any,
    ) -> AIGenerationResult:
        """Analyze multimodal input (text + images) and return structured reasoning."""
        pass

    @abstractmethod
    def get_metadata(self) -> AIProviderMetadata:
        """Return provider and active model metadata."""
        pass
