"""create_ai_usage_logs_table

Revision ID: d20a23ed03eb
Revises: dc472792e843
Create Date: 2026-09-13 00:16:12.207412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20a23ed03eb'
down_revision: Union[str, None] = 'dc472792e843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_logs_created_at'), 'ai_usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_model'), 'ai_usage_logs', ['model'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_provider'), 'ai_usage_logs', ['provider'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_request_id'), 'ai_usage_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_success'), 'ai_usage_logs', ['success'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_user_id'), 'ai_usage_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_usage_logs_user_id'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_success'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_request_id'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_provider'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_model'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_created_at'), table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    # ### end Alembic commands ###
