"""add_auth_fields_to_users_and_sessions

Revision ID: dc472792e843
Revises: 56c975f2460b
Create Date: 2026-09-12 22:22:34.988978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc472792e843'
down_revision: Union[str, None] = '56c975f2460b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('token_hash', sa.String(length=64), nullable=False))
    op.add_column('sessions', sa.Column('is_revoked', sa.Boolean(), nullable=False))
    op.add_column('sessions', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('sessions', sa.Column('user_agent', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_sessions_is_revoked'), 'sessions', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_is_revoked'), table_name='sessions')
    op.drop_column('sessions', 'user_agent')
    op.drop_column('sessions', 'ip_address')
    op.drop_column('sessions', 'is_revoked')
    op.drop_column('sessions', 'token_hash')
    # ### end Alembic commands ###
